/// Model serialization plumbing.
///
/// Field-level converters are generated by `firestore_odm_builder`. This file
/// only carries the shared typedefs and the small native value helpers that
/// generated code relies on. DateTime maps natively to Firestore Timestamp
/// (both directions, handled by `cloud_firestore`); Duration maps to an int of
/// microseconds by convention.
library;

import 'package:cloud_firestore/cloud_firestore.dart' show Blob, GeoPoint;


/// Converts a `Duration` to Firestore microseconds (int).
dynamic durationToJson(Duration value) => value.inMicroseconds;

/// Converts a Firestore microseconds value (int) back to [Duration].
Duration durationFromJson(dynamic value) =>
    Duration(microseconds: value as int);

/// Identity for values Firestore stores natively (DateTime, Timestamp,
/// GeoPoint, Blob, DocumentReference, primitives).
T identity<T>(T value) => value;

/// Identity from-JSON helper for values Firestore returns natively.
T identityFromJson<T>(dynamic value) => value as T;

/// Static registry of the converters that need no model-specific codegen.
abstract final class FirestoreConverters {
  static dynamic durationToJson(Duration value) => value.inMicroseconds;
  static Duration durationFromJson(dynamic value) =>
      Duration(microseconds: value as int);
  static Blob bytesToJson(Object? value) => value as Blob;
  static Object? bytesFromJson(Blob value) => value;
  static GeoPoint geoPointToJson(GeoPoint value) => value;
  static GeoPoint geoPointFromJson(dynamic value) => value as GeoPoint;
}
